variable "name" {
  description = "Cloud SQL instance name. Note: names cannot be reused for ~7 days after deletion."
  type        = string

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{0,96}$", var.name))
    error_message = "name must be lowercase alphanumeric/hyphen characters starting with a letter."
  }
}

variable "project_id" {
  description = "GCP project ID."
  type        = string
}

variable "region" {
  description = "GCP region."
  type        = string
}

variable "database_version" {
  description = "PostgreSQL version."
  type        = string
  default     = "POSTGRES_16"

  validation {
    condition     = can(regex("^POSTGRES_[0-9]+$", var.database_version))
    error_message = "database_version must look like POSTGRES_16."
  }
}

variable "tier" {
  description = "Machine tier (e.g. db-custom-4-16384)."
  type        = string
  default     = "db-custom-2-8192"
}

variable "availability_type" {
  description = "REGIONAL (HA with standby) or ZONAL."
  type        = string
  default     = "REGIONAL"

  validation {
    condition     = contains(["REGIONAL", "ZONAL"], var.availability_type)
    error_message = "availability_type must be REGIONAL or ZONAL."
  }
}

variable "disk_size_gb" {
  description = "Initial disk size (GiB); autoresize is enabled."
  type        = number
  default     = 100
}

variable "network" {
  description = "VPC self link for private IP. A Service Networking peering (servicenetworking.googleapis.com) must already exist on this network."
  type        = string
}

variable "cmek_key_name" {
  description = "Optional CMEK key (projects/.../cryptoKeys/...). The Cloud SQL service agent needs encrypter/decrypter on it. Null uses Google-managed encryption."
  type        = string
  default     = null
}

variable "database_name" {
  description = "Initial database to create."
  type        = string
  default     = "tap"
}

variable "username" {
  description = "Initial SQL user (password generated by Terraform; read it from the output)."
  type        = string
  default     = "tap_admin"
}

variable "backup_start_time" {
  description = "Daily backup window start (HH:MM, UTC)."
  type        = string
  default     = "02:00"

  validation {
    condition     = can(regex("^([01][0-9]|2[0-3]):[0-5][0-9]$", var.backup_start_time))
    error_message = "backup_start_time must be HH:MM (24h)."
  }
}

variable "retained_backups" {
  description = "Number of automated backups retained."
  type        = number
  default     = 14
}

variable "transaction_log_retention_days" {
  description = "PITR transaction log retention (1-7 days)."
  type        = number
  default     = 7

  validation {
    condition     = var.transaction_log_retention_days >= 1 && var.transaction_log_retention_days <= 7
    error_message = "transaction_log_retention_days must be 1-7."
  }
}

variable "database_flags" {
  description = "Postgres flags: name => value."
  type        = map(string)
  default     = {}
}

variable "deletion_protection" {
  description = "Both Terraform-level and API-level deletion protection."
  type        = bool
  default     = true
}

variable "labels" {
  description = "User labels applied to the instance."
  type        = map(string)
  default     = {}
}
